#!/bin/bash
scss_theme="$HOME/.config/eww/whimsy/theme.scss"
# dark="oxocarbon"
# light="oxocarbon_light"

switch_theme () {
    echo '@import '"\"./themes/$1.scss\"" > $scss_theme

    if [[ -f "$HOME/.config/foot/themes/$1.ini" ]]; then
        sed -i "s/include=.*/include=~\/.config\/foot\/themes\/$1.ini/" $HOME/.config/foot/foot.ini
    fi

    if [[ -f "$HOME/.config/wofi/themes/$1.css" ]]; then 
        sed -i "s/@import.*/@import \".config\/wofi\/themes\/$1.css\";/" $HOME/.config/wofi/style.css
    fi

    inactivebg=$(sed -n "s/\$surface0: \(.*\);/\1/p" $HOME/.config/eww/whimsy/themes/$1.scss)
    bg=$(sed -n "s/\$surface1: \(.*\);/\1/p" $HOME/.config/eww/whimsy/themes/$1.scss)
    text=$(sed -n "s/\$white0: \(.*\);/\1/p" $HOME/.config/eww/whimsy/themes/$1.scss)
    urgent=$(sed -n "s/\$red: \(.*\);/\1/p" $HOME/.config/eww/whimsy/themes/$1.scss)

    if [ -n $surface0 ] && [ -n $surface2 ] && [ -n $white0 ]; then
        swaymsg "client.focused          $bg           $bg          $text          $bg"
        swaymsg "client.unfocused        $inactivebg $inactivebg $text  $inactivebg"
        swaymsg "client.focused_inactive $inactivebg $inactivebg $text  $inactivebg"
        swaymsg "client.urgent           $urgent    $urgent   $text          $urgent"
    fi

    swaymsg output \* bg $2 fill

    sleep 1
    notify-send -i $2 -a Theme "Theme selected" "$1"
}

current=`cat $scss_theme | sed 's/@import \".\/themes\/\(.*\).scss\"/\1/'`

if [[ $1 == "select" ]]; then
    case $2 in 
    "oxocarbon_light")
        switch_theme "oxocarbon_light" "~/.config/sway/wallpaper/flowerbw.png"
        ;;
    "catppuccin") 
        switch_theme "catppuccin" "~/.config/sway/wallpaper/rocket.png"
        ;;
    "catppuccin_latte") 
        switch_theme "catppuccin_latte" "~/.config/sway/wallpaper/whitebgfw.jpg"
        ;;
    "rosepine") 
        switch_theme "rosepine" "~/.config/sway/wallpaper/rosepine.jpg"
        ;;
    "swamp") 
        switch_theme "swamp" "~/.config/sway/wallpaper/swamp.png"
        ;;
    "biscuit") 
        switch_theme "biscuit" "~/.config/sway/wallpaper/biscuitcat.png"
        ;;
    "camellia") 
        switch_theme "camellia" "~/.config/sway/wallpaper/camelliawoman.jpg"
        ;;
    *)
        switch_theme "oxocarbon" "~/.config/sway/wallpaper/flowerbw.png"
        ;;
    esac
elif [[ $1 == "setup" ]]; then
    case $current in 
    "oxocarbon_light")
        switch_theme "oxocarbon_light" "~/.config/sway/wallpaper/flowerbw.png"
        ;;
    "catppuccin") 
        switch_theme "catppuccin" "~/.config/sway/wallpaper/catppuccinlan.png"
        ;;
    "catppuccin_latte") 
        switch_theme "catppuccin_latte" "~/Downloads/images/cloudcity.png"
        ;;
    "rosepine") 
        switch_theme "rosepine" "~/.config/sway/wallpaper/rosepine.jpg"
        ;;
    "swamp") 
        switch_theme "swamp" "~/.config/sway/wallpaper/swamp.png"
        ;;
    "biscuit") 
        switch_theme "biscuit" "~/.config/sway/wallpaper/biscuitcat.png"
        ;;
    "camellia") 
        switch_theme "camellia" "~/.config/sway/wallpaper/camelliawoman.jpg"
        ;;
    *)
        switch_theme "oxocarbon" "~/.config/sway/wallpaper/flowerbw.png"
        ;;
    esac
else
    echo $current
fi
